name: Docker Doxygen with Doxypypy

on:
  push:
    paths:
      - "doxygen-doxypypy/**"
  pull_request:
    paths:
      - "doxygen-doxypypy/**"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Build Doxygen with Doxypypy
        run: |
          cd doxygen-doxypypy
          /bin/bash build.sh
      - name: Cache Docker image
        uses: actions/cache@v3.3.0
        env:
            cache-name: cache-docker
        with:
            path: |
                ~/docker
            key: ${{ runner.os }}-build-${{ env.cache-name }}-doxygen-doxypypy
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-
                ${{ runner.os }}-build-
                ${{ runner.os }}-

  publish:
    runs-on: "ubuntu-latest"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/doxygen-doxypypy-v')
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Cache Docker image
        uses: actions/cache@v3.3.0
        env:
            cache-name: cache-docker
        with:
            path: |
                ~/docker
            key: ${{ runner.os }}-build-${{ env.cache-name }}-doxygen-doxypypy
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}
                ${{ runner.os }}-build-
                ${{ runner.os }}-
      - name: Pull cached docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker load < ~/docker/doxygen-doxypypy.tar.gz
          docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}
          docker push toliak/doxygen-doxypypy:latest
          docker push toliak/doxygen-doxypypy:$(cat doxygen-doxypypy/version)